import random

from coincollector_mazes.get_maze import get_maze, print_maze_info
from coincollector_mazes.refine_maze import add_new_edges


def generate_maze_data_with_seed(seed: int, number_of_mazes: int, difficulty_level=250, circles=0) -> list:
    '''
    Generates a list of Coin-Collector mazes.

    Args:
        seed: seed used to generate seeds for map generation.
        number_of_mazes: number of mazes generated.
        difficulty_level: 10 for short line graphs; 250 for long levels which are not line graphs.
        circles: number of circles to be added to the tree generated by standard Textworld method.

    Returns:
        A list of network-x graphs encoding Coin-Collector mazes.
    '''
    random.seed(seed)
    maze_list = []
    for k in range(number_of_mazes):
        print('Generating maze %s of %s...' % (k, number_of_mazes))
        this_seed = random.randint(1,100000)
        maze = get_maze(difficulty_level, this_seed)
        if circles>0:
            print('Adding circles to maze...')
            maze = add_new_edges(maze, circles, this_seed)
        maze_list += [maze]
    return maze_list


if __name__ == '__main__':
    number_of_mazes = 10
    maze_list = generate_maze_data_with_seed(100, number_of_mazes, difficulty_level=250, circles=200)
    print_maze_info(maze_list[0])
    print(len(maze_list))
