import torch
def get_hyperparameters():
    return {
        "dim_latent": 64,
        "dim_nodes_AugmentingPath": 1,
        "dim_nodes_AugmentingPath_integers": 1,
        "dim_nodes_BFS": 1,
        "dim_nodes_BellmanFord": 1,
        "dim_target": 2,
        "dim_edges": 2,
        "dim_edges_BFS": 1,
        "dim_edges_BellmanFord": 1,
        "dim_bits": 8,
        "pna_aggregators": "mean min max std",
        "pna_scalers": "identity amplification attenuation",
        "batch_size": 32,
        "test_batch_size": 5,
        "walk_length": 5,
        "max_threshold": 10,
        "patience_limit": 20,
        "growth_rate_sigmoid": 0.0020,
        "sigmoid_offset": -300,
        # "device": "cuda" if torch.cuda.is_available() else "cpu",
        "device": "cpu",
        "calculate_termination_statistics": True,
        "lr": 0.00100,
        "weight_decay": 5e-4,
        "test_lr": 0.00100,
        "test_weight_decay": 5e-4,
        "bias": False,
    }
